version: "3.7"
services:
    web:
        image: base-node-app
        build: .
        ports:
            - 8080:8080
        volumes: 
            - ./:/app
        depends_on:
            - mongo
    
    mongo:
        image: mongo
        ports:
            - 27017:27017